services:
  geoipupdate:
    image: maxmindinc/geoipupdate
    environment:
      GEOIPUPDATE_ACCOUNT_ID:
      GEOIPUPDATE_LICENSE_KEY:
      GEOIPUPDATE_EDITION_IDS:
      
      GEOIPUPDATE_FREQUENCY:
      GEOIPUPDATE_HOST:
      GEOIPUPDATE_PROXY:
      GEOIPUPDATE_PROXY_USER_PASSWORD:
      GEOIPUPDATE_PRESERVE_FILE_TIMES:
      GEOIPUPDATE_VERBOSE:
    volumes:
      - $PWD/.geoip:/usr/share/GeoIP
  
  httprec:
    build: .
    image: telkomindonesia/httpmsg-enricher
    environment:
      HTTPMSG_ENRICHER_S3_ENDPOINT:
      HTTPMSG_ENRICHER_S3_REGION:
      HTTPMSG_ENRICHER_S3_FORCE_PATH_STYLE:
      HTTPMSG_ENRICHER_S3_CREDENTIAL_ACCESS_KEY_ID:
      HTTPMSG_ENRICHER_S3_CREDENTIAL_SECRET_ACCESS_KEY:
      HTTPMSG_ENRICHER_S3_BUCKET:

      HTTPMSG_ENRICHER_GEOIP_CITY_DB_PATH:
    volumes:
      - $PWD/.geoip:/app/.geoip
    ports:
      - 8080:8080